# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ssh_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
